# Generated by Django 4.0.4 on 2022-05-09 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaving_city', models.CharField(max_length=255, verbose_name='Leaving City')),
                ('going_city', models.CharField(max_length=255, verbose_name='Going City')),
                ('date', models.DateField()),
                ('leaving_time', models.TimeField()),
                ('coming_time', models.TimeField()),
                ('passengers', models.IntegerField()),
                ('price', models.IntegerField(default='Free')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
