# Generated by Django 4.0.4 on 2022-05-09 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='car',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Model of Car'),
            preserve_default=False,
        ),
    ]
