# Generated by Django 4.0.4 on 2022-05-09 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0002_drive_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
