# Generated by Django 4.0.4 on 2022-05-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0003_drive_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='price',
            field=models.CharField(default='Free', max_length=50),
        ),
    ]
