# Generated by Django 4.0.4 on 2022-05-18 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drives', '0004_alter_drive_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
